#!/bin/sh
#
# Usage: enve-fire [OPTIONS] [<TARGET>] [PATH] [--] [<command>] [<args...>]
#        enve-fire [OPTIONS] [shell] [PATH] [SCRIPT]
#        enve-fire [OPTIONS] [PATH] -c string
#        enve-fire [OPTIONS] window [PATH]
#        enve-fire [OPTIONS] boot [PRESET] [PATH]
# Environment encapsulation tool
#
# TARGET default is 'auto'
# PATH default is '.'
#
# Options:
#     -f, --file FILE         parse config from the file
#     -i, --include FILE      include config from the file
#     -r, --role ROLES
#     -o, --config KEY=VALUE  append a key-value pair to config
#     -e, --refresh           refresh current shell environment
#     -c, --script            run as shell script
#     --rcfile
#
# Target:
#     shell                   enter a interactive shell for the environment
#     window (*)
#     run                     run command in the environment
#     build (*)               run building process
#     test (*)                run testing process
#     pack (*)                run packing up process
#     pre-commit (*)
#
#
# _enve_fire() {
#     local state state_descr line
#     _arguments \
#         '(-f --file)'{-f,--file}'[main profile]:profile path:_files' \
#         '*'{-i,--include}'[incloud profile]:profile path:_files' \
#         '*'{-c,--config}'[config]:set config:->setconfig' \
#         '1:target:(shell run terminal)'
# }
#
# __noexec__=true

# shellcheck source=libexec/enve/baselib
. "$ENVE_HOME/enve/baselib"


settrace

# shellcheck source=libexec/enve/tablelib
. "$ENVE_HOME/enve/tablelib"

# shellcheck source=libexec/enve/wslib
. "$ENVE_HOME/enve/wslib"

# shellcheck source=libexec/enve/envelib2
. "$ENVE_HOME/enve/envelib"



ENVE_CONFIG_TEXT=${ENVE_PRECONFIG:+${ENVE_PRECONFIG%$newl}$newl}
cmd=
arg=
_main_profile=
assign_main_profile() {
    if [ -n "$_main_profile" ]; then
        die "cannot assign more then one main profile"
    fi
    _main_profile=$1
    while [ "${_main_profile%@*}" != "${_main_profile}" ]; do
        _suffix=${_main_profile##*@}
        if [ -z "$_suffix" ] || [ "${_suffix##*.*}" ]; then
            break
        fi
        if [ -z "${TARGET:-}" ]; then
            case $_suffix in
                shell|run|window|build|test|pack)
                    TARGET=$_suffix
                    ;;
            esac
        fi
        ENVE_ROLES="${ENVE_ROLES:+$ENVE_ROLES,}$_suffix"
        _main_profile=${_main_profile%"@$_suffix"}
    done
    if [ -d "${_main_profile}/.git" ]; then
        # TODO: git repo, do version checkout
        :
    elif [ "${_main_profile%.git}" != "${_main_profile}" ]; then
        # TODO: git repo, do version checkout
        :
    elif [ -d "${_main_profile}" ]; then
        # TODO: normal dir
        :
    fi
    ENVE_CONFIG_TEXT="${ENVE_CONFIG_TEXT}inherit=${_main_profile}$newl"
    ENVE_CONFIG_TEXT="${ENVE_CONFIG_TEXT}${ENVE_CONFIG:+${ENVE_CONFIG%$newl}$newl}"
}



while [ $# -gt 0 ]; do
    case $1 in
        -f|--file)
                case ${2:-} in -*|'')
                    die "you must supply a file path after $1" ;; esac
                assign_main_profile "$2"
                shift 2
            ;;
        -i|--include)
                case ${2:-} in -*|'')
                    die "you must supply a file path after $1" ;; esac
                ENVE_CONFIG_TEXT="${ENVE_CONFIG_TEXT}include=$2$newl"
                shift 2
            ;;
        -o|--config)
                case ${2:-} in
                    -*)
                            die "you must supply a vaild key-value pair after $1"
                        ;;
                    *=*);;
                    *)
                            die "you must supply a vaild key-value pair after $1"
                        ;;
                esac
                ENVE_CONFIG_TEXT="${ENVE_CONFIG_TEXT}$2$newl"
                shift 2
            ;;
        -r|--role)
                case ${2:-} in -*|'')
                    die "you must supply a role after $1" ;; esac
                ENVE_ROLES="${ENVE_ROLES:+$ENVE_ROLES,}$2"
                shift 2
            ;;
        -c|--script)
                case ${2:-} in -*|'')
                    die "-c: option requires an argument" ;; esac
                EXEC_ARG1_AS_SCRIPT=1
                shift 1
            ;;
        --rcfile)
                RCFILE_STARTUP=1
                shift 1
            ;;
        --rescure)
                EXEC_RESCURE=1
                shift 1
            ;;
        --debug0)
                debug_mode=0
                shift 1
            ;;
        --debug|--debug1)
                debug_mode=1
                shift 1
            ;;
        --debug2)
                debug_mode=2
                shift 1
            ;;
        --debug3)
                debug_mode=3
                shift 1
            ;;
        --debug4)
                debug_mode=4
                shift 1
            ;;
        --help)
                print_program_help "$ENVE_PROGRAM" >&2
                quiet_exit 1
            ;;
        --)
                cmd=${cmd:-auto}
                shift 1
                break
            ;;
        -*)
                die "unknown option: $1"
            ;;
        *)
                if [ -z "$cmd" ]; then
                    case $1 in
                        shell|window|run|build|test|pack)
                                cmd=$1
                                shift
                                continue
                            ;;
                        boot)
                                shift
                                if [ -n "${1:-}" ]; then
                                    subtype=$1
                                    shift
                                fi
                                EXEC_RESCURE=1
                                _profile="$ENVE_HOME/enve/preset/boot${subtype:+"-$subtype"}.enve.ini"
                                assign_main_profile "$_profile"
                                unset _profile
                                cmd=auto
                                break
                            ;;
                    esac
                fi
                if [ -z "$_main_profile${arg:-}" ]; then
                    arg=$1
                    shift
                else
                    # "$1" is ARG1
                    [ "$cmd" = auto ] && cmd=run
                    break
                fi
            # if [ -z "$cmd" ]; then
            #     case $1 in
            #         shell|window|run|build|test|pack)
            #                 cmd=$1
            #                 shift
            #                 continue
            #             ;;
            #         boot)
            #                 shift
            #                 if [ -n "${1:-}" ]; then
            #                     subtype=$1
            #                     shift
            #                 fi
            #                 EXEC_RESCURE=1
            #                 _profile="$ENVE_HOME/enve/preset/boot${subtype:+"-$subtype"}.enve.ini"
            #                 assign_main_profile "$_profile"
            #                 unset _profile
            #                 cmd=auto
            #                 break
            #             ;;
            #         *)
            #                 cmd=auto
            #                 unset ARG_RESULT ARG_REMOTE ARG_WS_PATH
            #                 parse_enve_argument "$1"
            #             ;;
            #     esac

            # elif [ -z "$_main_profile" ]; then
            #     unset ARG_RESULT ARG_REMOTE ARG_WS_PATH
            #     parse_enve_argument "$1"

            # else
            #     # "$1" is ARG1
            #     [ "$cmd" = auto ] && cmd=run
            #     break
            # fi

            # case $ARG_RESULT in
            #     ini)
            #             if [ -e "$1/enve.ini" ]; then
            #                 assign_main_profile "$1/enve.ini"
            #             else
            #                 assign_main_profile "$1"
            #             fi
            #         ;;
            #     repo)
            #             # shellcheck source=libexec/enve/urlutils
            #             . "$ENVE_HOME/enve/urlutils"
            #             repo=$(enve_clone_tmp "$1")
            #             assign_main_profile "$repo/enve.ini"
            #         ;;
            #     ws)
            #             if [ -n "$ARG_REMOTE" ]; then
            #                 # TODO: ARG_WS_PATH -> ARG_PATH
            #                 ENVE_SSH_REMOTE=$ARG_REMOTE
            #                 RCFILE_PATH=$(run_enve enve fire
            #                               --rcfile shell ":$ARG_WS_PATH")
            #             else
            #                 get_workspace_config_path "$1"
            #                 assign_main_profile "$WS_CONFIG_DIR/enve.ini"
            #             fi
            #         ;;
            #     null)
            #             break
            #         ;;
            # esac
            # shift
            # if [ "${1##*/}" != "$1" ] || [ "${1##*.}" != "$1" ]; then
            #     cmd=auto
            #     assign_main_profile "$1"
            #     shift
            # else
            #     _error "unknown command: $1"
            #     print_program_help "$ENVE_PROGRAM" >&2
            #     die
            # fi
        ;;

    esac
done

[ "${cmd:-auto}" = auto ] && cmd=shell

if [ "$cmd" = shell ] && [ $# -eq 1 ]; then
    EXEC_ARG1_AS_SCRIPT=1
fi

# if [ -z "${_main_profile}" ]; then
#     if [ -e "./enve.ini" ]; then
#         assign_main_profile "./enve.ini"
#     elif [ "$cmd" = shell ]; then
#         EXEC_RESCURE=1
#         assign_main_profile "$ENVE_HOME/enve/preset/boot.enve.ini"
#     else
#         error "require config path"
#         print_program_help fire2 >&2
#         die
#     fi
# fi


if [ -z "$_main_profile" ]; then
    unset ARG_RESULT ARG_REMOTE ARG_PATH ARG_ROLES
    unset WS_CONFIG_DIR PROJECT_DIR
    parse_enve_argument "${arg:-"."}"
    if [ "${ARG_RESULT:-}" = 'repo' ]; then
        # shellcheck source=libexec/enve/urlutils
        . "$ENVE_HOME/enve/urlutils"
        repo=$(enve_clone_tmp "$arg")
        if [ -f "$repo/enve.ini" ]; then
            assign_main_profile "$repo/enve.ini"
        else
            die "'$repo' has no 'enve.ini' inside"
        fi
    elif [ -z "${ARG_REMOTE:-}" ]; then
        if [ -z "${ARG_PATH:-}" ]; then
            # default is current directory
            ARG_PATH=.
        fi
        p=$ARG_PATH
        if find_project_upward "$ARG_PATH"; then
            assign_main_profile "$PROJECT_DIR/enve.ini"
        fi
    else
        # TODO: remote
        exec ssh "$ARG_REMOTE" enve config ":$ARG_PATH"
        return 0
    fi
else
    PROJECT_DIR=${_main_profile%"/enve.ini"}
fi

if [ "${ARG_RESULT:-}" != 'repo' ]; then
    find_ws_upward "${PROJECT_DIR:-$ARG_PATH}"
    if [ -n "${WS_CONFIG_DIR:-}" ]; then
        if [ -n "${_main_profile}" ]; then
            [ -f "$WS_CONFIG_DIR/enve.ini" ] && \
                ENVE_CONFIG_TEXT="include=$WS_CONFIG_DIR/enve.ini$newl${ENVE_CONFIG_TEXT}"
        else
            # default is workspace
            [ -f "$WS_CONFIG_DIR/enve.ini" ] && \
                assign_main_profile "$WS_CONFIG_DIR/enve.ini"
            PROJECT_DIR=$ENVE_WORKSPACE
        fi
    fi
fi

if [ -n "${EXEC_SHIELD:-}" ]; then
    # 這樣shield結束之後，可以直接進到漂亮的命令列。
    ENVE_ROLES="shell,${ENVE_ROLES:-}"
    ENVE_CONFIG_TEXT="${ENVE_CONFIG_TEXT}core.target=shell$newl"
else
    ENVE_ROLES="$cmd,${ENVE_ROLES:-}"
    ENVE_CONFIG_TEXT="${ENVE_CONFIG_TEXT}core.target=$cmd$newl"
fi

s=${ENVE_ROLES:-}${ARG_ROLES:+,"$ARG_ROLES"}
replace '@' ','
fast_system_roles
ENVE_ROLES="$s${out_system_roles:+,"$out_system_roles"}"

if [ "${debug_mode:-}" = "0" ]; then
    get_system2
    echo "MACHINE: $MACHINE" >&2
    echo "KERNEL: $KERNEL" >&2
    echo "KERNEL_VERSION: $KERNEL_VERSION" >&2
    echo "" >&2
    echo "ENVE_WORKSPACE: $ENVE_WORKSPACE" >&2
    echo "ENVE_LOCAL_SYSROOT: $ENVE_LOCAL_SYSROOT" >&2
    echo "ENVE_VAR_DIR: $ENVE_VAR_DIR" >&2
    echo "ENVE_DATA_DIR: $ENVE_DATA_DIR" >&2

    ensure_caches
    echo "" >&2
    echo "ENVE_HOME: $ENVE_HOME" >&2
    echo "ENVE_CACHE_DIR: $ENVE_CACHE_DIR" >&2
    return 0
elif [ "${debug_mode:-}" = "1" ]; then
    if ! ENVE_HOSTNAME=$(hostname); then
        ENVE_HOSTNAME=localhost
    fi
    echo "WS  : $ENVE_HOSTNAME:$ENVE_WORKSPACE" >&2
    echo "ENVE: $PROJECT_DIR@${ENVE_ROLES#,}" >&2
    echo "CMD : ${cmd:-}" >&2
    echo "ARGS: $*" >&2
    echo "ENVE_CONFIG_TEXT:" >&2
    echo "$ENVE_CONFIG_TEXT" >&2
    return 0
elif [ "${debug_mode:-}" = "2" ]; then
    TABLE=
    if !    stage1_is_text=1 \
            roles="$ENVE_ROLES" loaded="" \
            parse_inherit="" \
            parse_profile_optional="" \
            enve_parse_config "$ENVE_CONFIG_TEXT"; then
        _error "parse_config failed"
        return 1
    fi
    printf %s "${TABLE:-$newl}"
    return 0
fi

case $cmd in
    run)
            EXEC_USE_EXEC=1 RCFILE_STARTUP=${RCFILE_STARTUP:-} fire2 "$@"
        ;;
    shell)
            EXEC_USE_EXEC=1 RCFILE_STARTUP=${RCFILE_STARTUP:-} fire2
        ;;
    '')
            print_program_help fire >&2
            die
        ;;
esac


