#!/bin/sh

# shellcheck disable=2016
true

if [ -n "${HAVE_ENVE_GITLIB:-}" ]; then
    return 0
fi
HAVE_ENVE_GITLIB=1

# shellcheck source=libexec/enve/baselib
. "$ENVE_HOME/enve/baselib"
# shellcheck source=libexec/enve/urlutils
. "$ENVE_HOME/enve/tablelib"

# 測試程式放在doc/confex-showcase.sh

: '

1. 不能修改主線歷史，也不能修改發布分支歷史，因為這兩者都有機會被引用。
   如果在主線中進行修復，再把補丁cherry-pick到發布分支。
   因此，對於不良的補丁，只能撤回補丁(revert)。
   如果要再次應用撤回的不良補丁，必須使用`--force-rebase`，因為git會忽略已經應用的補丁。
   而在開發分支中，則沒有這個限制，直接刪除撤回即可。

2. 發布分支要不要連成一線，取決於要不要強調發布設定的變化。(?)
   如果決定連成一線，每次發布新版本就把主線merge到發布分支。


## 抽象虛化分支

- 抽象介面: 定義輸出輸入以及功能，而不是具體實作。
- 虛假實作: 並沒有實際具有該功能的實作，而只是符合抽象介面。

例如系統中有A組件與B組件互相依賴，但AB由兩個不同團隊所維護。
而某個時間點，A組件與B組件都要同時將其實作進行大規模改版。
我們可以做出A抽象與B抽象，讓B依賴A抽象，讓A依賴B抽象。
並且調換A與B抽象的背後的實作，為虛假實作。

這時AB可以同時進行改版而不互相影像。
A改版結束之後只要調換A抽象的實作為新的A`。
B改版結束之後只要調換A抽象的實作為新的B`。
於是AB同時完成改版。

無論是「功能開關」還是「抽象分支」，可以放在編譯期配置，也可以放在執行期配置。

然而 Feature Toggle類似於if else機制 一定程度會讓代碼變脆弱
Feature Toggle建立有良好的代碼架構上 才比較適合使用



## 模組換配、挑選換配，反轉換配

換配Ａ - 啟用測試模式
修改１
換配Ｂ - 將甲模組升級到2.0
修改２
換配Ｃ - 將乙模組升級到3.0
修改３
修改４

要將上述支線並到主線時，
利用`checkout master; rebase -i feature --exec "enve test"`
執行如下過程，rebase 到主線最前端

// 先pick要合併的換配
pick 換配Ｂ (但由於甲模組在之後的主線已經是2.0，所以這個pick實際上不生效)
pick 換配Ｃ
// 再pick要合併的非換配
pick 修改１，exec測試通過
pick 修改２，exec測試不通過（因為不通過，下一個pick改成fixup）
fixup 修改３，exec測試通過
// 最後pick不合併的提交
pick 換配Ａ
pick 修改４

最後的結果是
換配Ｃ
修改１
修改３ (master)
換配Ａ
修改４ (feature)

詳細過程可以參考教學 https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
'

is_branch_exists() {
    git rev-parse --verify "$1" 2>/dev/null
    return $?
}

is_inside_rebase() {
    git rebase --show-current-patch 1>&2 2>/dev/null
    return $?
}

get_current_branch_name() {
    git symbolic-ref --short HEAD
}

get_current_confex_branch() {
    # for branch in $(git --no-pager branch --list --format "%(refname:short)"); do
    #     if [ -n "$branch" ] && [ "$branch" != "${branch%%confexing/}" ]; then
    #         echo "${branch%%confexing/}"
    #         return 0
    #     fi
    # done
    # return 1
    request_name=
    target=
    br=
    for branch in $(git --no-pager tag); do
        if [ -n "$branch" ] && [ "$branch" != "${branch#confexing/}" ]; then
            # branch=${branch#confexing/}
            # target=${branch##*/}
            # br=${branch%/to/"$target"}
            IFS=/ read request_name br target <<EOF
${branch#confexing/}
EOF
            if [ -n "$request_name" ] && [ -n "$br" ] && [ -n "$target" ]; then
                return 0
            fi
        fi
    done
    request_name=
    target=
    br=
    return 1
}

abort() {
  printf "%s\n" "$@" >&2
  exit 1
}

shell_join() {
    printf "%s" "$1"
    shift
    for s in "$@"; do
        replace " " "\\ "
        printf " "
        printf "%s" "$s"
    done
}

execute() {
    if ! "$@"; then
        abort "$(printf "Failed during: %s" "$(shell_join "$@")")"
    else
        printf "execute %s\\n" "$(shell_join "$@")"
    fi
}

USABLE_GIT=git

clone_to() {
    execute mkdir -p "$CLONE_TO"
    cd "$CLONE_TO" >/dev/null || return

    if [ -z "${NONINTERACTIVE-}" ]; then
        quiet_progress="--quiet --progress"
    else
        quiet_progress="--quiet"
    fi

    execute "${USABLE_GIT}" -c init.defaultBranch=master init --quiet
    execute "${USABLE_GIT}" config set remote.origin.url "${GIT_REMOTE_URL}"
    execute "${USABLE_GIT}" config set remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    execute "${USABLE_GIT}" config set --bool "core.autocrlf" "false"
    execute "${USABLE_GIT}" config set "core.eol" "lf"
    # execute "${USABLE_GIT}" config set --bool "core.symlinks" "true"
    execute "${USABLE_GIT}" fetch --force $quiet_progress origin
    execute "${USABLE_GIT}" fetch --force $quiet_progress --tags origin
    # execute "${USABLE_GIT}" fetch --force $quiet_progress \
    #     origin "refs/heads/master:refs/remotes/origin/master"
    execute "${USABLE_GIT}" remote set-head origin --auto >/dev/null
    execute "${USABLE_GIT}" reset --hard origin/master

  #   LATEST_GIT_TAG="$("${USABLE_GIT}" tag --list --sort="-version:refname" | head -n1)"
  # if [[ -z "${LATEST_GIT_TAG}" ]]
  # then
  #   abort "Failed to query latest Homebrew/brew Git tag."
  # fi
  # execute "${USABLE_GIT}" "checkout" "--quiet" "--force" "-B" "stable" "${LATEST_GIT_TAG}"

}


confex_to() {
    if is_inside_rebase; then
        echo "your engage rebasing, try 'rebase --abort' first" >&2
        return 1
    elif is_branch_exists request; then
        echo "request exists. use --abort to exit rebase" >&2
        return 1
    elif get_current_confex_branch; then
        echo "fatch: other branch $br is confexing" >&2
        return 1
    elif [ -z "${1:-}" ]; then
        echo "confex target undefined" >&2
        return 1
    elif ! is_branch_exists "$1"; then
        echo "confex target '$1' not exists" >&2
        return 1
    fi

    target=$1
    request_name=${2:-request}

    br=$(get_current_branch_name)
    # git tag --force confexing/$br/to/$target
    git checkout -b __request
    if is_branch_exists tail/$br &&
       ! git merge-base --is-ancestor tail/$br $target; then
        # 當tail/$br不再是$target的祖節點時，以tail/$br作為最尾端
        tail=tail/$br
    else
        tail=$target
    fi

    # rebase同時也要改變committer，這樣才和merge的操作一樣
    fmt='%s%nexec GIT_COMMITTER_DATE="%cD" GIT_COMMITTER_NAME="%cn" GIT_COMMITTER_EMAIL="%ce" git commit --amend --no-edit'
    if git -c rebase.instructionFormat="$fmt" \
                rebase -i --empty=drop --autosquash --onto $target $tail __request; then
        git tag --force confexing/$request_name/$br/to/$target
        _make_request
    elif is_inside_rebase; then
        git tag --force confexing/$request_name/$br/to/$target
    else
        # rebase nothing or other error
        _exit_confex
        # git switch $br
        # git branch --delete --force __request
        # git tag --delete confexing/$br/to/$target
    fi
}

confex_continue() {
    if is_inside_rebase; then
        echo "your engage rebasing, try 'rebase --abort' first" >&2
        return 1
    elif ! is_branch_exists __request; then
        echo "nothing to continue" >&2
        return 1
    elif ! get_current_confex_branch; then
        echo "nothing to continue, confexing not found" >&2
        return 1
    fi
    _make_request
}

_make_request() {
    if ! git switch __request; then
        return 1
    fi
    git checkout -b $request_name
    git branch --delete --force __request
}

_exit_confex() {
    git switch $br
    git branch --delete --force __request
    git branch --delete --force $request_name
    git tag --delete confexing/$request_name/$br/to/$target
}

confex_abort() {
    if is_inside_rebase; then
        echo "your engage rebasing, try 'rebase --abort' first" >&2
        return 1
    elif ! get_current_confex_branch; then
        echo "nothing to abort, confexing not found" >&2
        return 1
    elif ! is_branch_exists $request_name; then
        echo "nothing to abort" >&2
        return 1
    fi
    _exit_confex
    # git switch $br
    # git branch --delete --force $request_name
    # git tag -d confexing/$br/to/$target
}

confex_finish() {
    # ## accept a pull request
    #
    # 1. git pull --rebase=merges origin $target
    # 2. 檢查 $request..$target 的 ancestor 是 remotes/origin/$target
    # 3. 否則 rebase $request 到新的 $target, 並且重新命名$request, 如果衝突則退出
    # 4. 測試 $request, 如果失敗則退出
    # 5. (X)進行 bump 作業 (可選)
    # 6. 對 $target update-ref to $request
    # 7. git push origin $target, 如果失敗則退出或回到步驟1
    # 8. 刪除 $request
    # 9. git push origin

    if is_inside_rebase; then
        echo "your engage rebasing, try 'rebase --abort' first" >&2
        return 1
    elif ! get_current_confex_branch; then
        echo "nothing to finish, confexing not found" >&2
        return 1
    elif ! is_branch_exists $request_name; then
        echo "request not exists, maybe rebase failed" >&2
        return 1
    fi

    # 首先更新 target
    # TODO: 這會切換分支
    # git pull --rebase=merges origin $target
    # 這不會切換分枝
    git fetch origin $target:$target

    if [ "$(git rev-parse)" != "$(git rev-parse)" ]; then
        echo "$target behind remote, this request needs to advance" >&2
        return 1
    fi

    if [ "${1:-}" = "--check" ]; then
        # TODO: 確定 notes 中有 Tests-Success: 字樣
        # git notes --ref testlog show
        shift 1
    fi
    if [ "${1:-}" = "--group" ]; then
        # --group "message": merge --no-ff 用來製造特殊紀錄
        message=${2:-}
        case $message in
            '') shift 1;;
            -*) message=; shift 1;;
            *)  shift 2;;
        esac
        git switch $target
        if [ -n "$message" ]; then
            git merge --no-ff -m "$message" $request_name
        else
            git merge --no-ff $request_name
        fi
    else
        echo "**** update-ref"
        git update-ref -m "fast-forwart $target to new rebased branch" \
            refs/heads/$target $request_name
    fi

    _exit_confex

    if [ "${1:-}" = "--update" ]; then
        # merge back to $br
        git merge --no-edit $target
        shift
    fi
    if [ "${1:-}" = "--tail" ]; then
        git tag -f tail/$br
        shift
    fi
}

test_mark() {
    git notes --ref test add -F test.file $request
    git notes --ref testlog add -F short-log.file $request
}

test_list() {
    GIT_NOTES_DISPLAY_REF=test git log
}

test_show() {
    # git pull --set-upstream remote 'refs/notes/*'
    # git push remote 'refs/notes/*'
    git notes --ref refs/notes/testlog show
}

bump() {
    # 只能用在request
    # 會創造一個新的commit
    # 裡面有new version還有CHANGELOG
    :
}

create_confex_branch() {
    # 指定要複製的confex
    # 或是製作新的confex
    :
}

deploy() {
    # 計算出哪個commit可以發布
    # 1. 必須在指定版本範圍內，包含主線或是hotfix branch
    # 2. 所有滿足測試條件或設定條件的commit
    # 3. 那之中的最新版本
    # 因此不需要
    # 1. version tag
    # 2. stage branch
    # 3. release branch
    # hotfix直接在主線中進行，只有這個時候會有hotfix branch
    # note: Last-Stable，會在穩定發佈一段時間後自動加上
    # 如果發生災難，可以回復到之前幾個 Last-Stable
    :
}
