.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ENVE\-BASE" "3" "October 2019" "" ""
.
.SH "NAME"
\fBenve\-base\fR \- basic functions
.
.P
\fBhascmd\fR \fIcommand\fR \fBreplace\fR s=? \fIold\fR \fInew\fR [\fIcount\fR] \fBhashstr\fR s=? \fBfast_readtext\fR \fIfile\fR \fBfast_dirname\fR d=? \fBfast_basename\fR d=?
.
.P
\fBmkstemp\fR \fIname\fR\.XXXXXX \fBmkdtemp\fR \fIname\fR\.XXXXXX
.
.P
\fBfast_get_cachedir\fR \fBget_cachedir\fR \fBfast_get_tempdir\fR \fBget_tempdir\fR
.
.P
\fBsave\fR [\fIargs\fR\.\.\.]
.
.P
save args to string
.
.P
\fBany_key_continue\fR
.
.P
\fBlog\fR loglevel=? [\fItext\fR\.\.\.] \fBlogtable\fR loglevel=? \fITABLE\fR
.
.P
\fB_fatal\fR \fItext\fR \fB_critical\fR \fItext\fR \fB_error\fR \fItext\fR \fB_warning\fR \fItext\fR \fB_notice\fR \fItext\fR \fB_info\fR \fItext\fR \fB_debug\fR \fItext\fR \fB_trace\fR \fItext\fR
.
.P
\fBdie\fR [\fItext\fR [\fIexitcode\fR]]
.
.P
\fBsettrace\fR
