.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ENVE\-TABLE" "3" "October 2019" "" ""
.
.SH "NAME"
\fBenve\-table\fR \- table manipulation functions
.
.SH "提要 SYNOPSIS"
\fB\. "$ENVE_HOME/enve/envelib"\fR
.
.SH "Constance"
.
.nf

tab=\'\et\'
feed=\'\ef\'
vtab=\'\ev\'
newl=\'\en\'
.
.fi
.
.SH "Function"
\fBtable_tail\fR \fImatch\fR [\fItype\fR]
.
.P
\fBtable_subset\fR \fImatch\fR [\fItype\fR]
.
.P
\fBtable_exclude\fR \fImatch\fR [\fItype\fR]
.
.P
\fBtable_substi\fR \fIvar_table\fR
.
.P
接下來的\fBas_*\fR系列都是管道函數，接收TABLE作為input，輸出特定格式的內容。
.
.P
\fBas_postfix\fR \fIpostfix\fR
.
.P
\fBas_rootkey\fR
.
.P
\fBas_value\fR
.
.P
\fBas_uniquekey\fR
.
.P
\fBas_concat\fR
.
.P
\fBout_item\fR \fItype\fR \fIkey\fR \fIvalue\fR \fBout_var\fR \fIkey\fR \fIvalue\fR \fBout_var_fast\fR \fIkey\fR \fIvalue\fR \fBout_var_just\fR \fIkey\fR \fIvalue\fR
.
.P
\fBout_alias\fR \fIkey\fR \fIvalue\fR \fBout_list\fR \fIkey\fR \fIvalue\fR \fBout_join\fR \fIkey\fR \fIvalue\fR \fBout_source\fR \fIkey\fR \fIvalue\fR \fBout_code\fR \fIkey\fR \fIvalue\fR \fBout_secret\fR \fIkey\fR \fIvalue\fR
.
.P
\fBparse_config_recursive\fR roles=? \fIfile\fR
.
.P
\fBenve_fire\fR ENVE_PROFILE=? ENVE_ROLES=? ENVE_CONFIG=? \fIRCFILE_PATH\fR
