.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ENVE" "1" "March 2019" "" ""
.
.SH "NAME"
\fBenve\fR \- list directory contents
.
.SH "SYNOPSIS"
\fBname\fR [\fIoptional\fR\.\.\.] \fIflags\fR
.
.SH "DESCRIPTION"
.
.SH "SECTION 1 \- WHAT"
.
.SH "OPTIONS"
.
.TP
\fB\-b\fR \fIfileeeeeeeeeeeeee\fR
True if \fIfile\fR exists and is a block special file\.
.
.TP
\fB\-c\fR \fIfile\fR
True if \fIfile\fR exists and is a character special file\.
.
.TP
\fB\-d\fR \fIfile\fR \fIfile2\fR
True if file exists and is a directory\.
.
.TP
\fB\-\-manual\fR=\fImanual\fR
The name of the manual this man page belongs to; \fImanual\fR is prominently displayed top\-center in the header area\.
.
.SH "SECTION 2"
See \fISECTION 1 \- WHAT\fR or [to put it another way][OPTIONS]\.
.
.SH "COPYRIGHT"
Ronn is Copyright (C) 2009 Ryan Tomayko \fIhttp://tomayko\.com/about\fR
.
.SH "SEE ALSO"
groff(1), man(1), pandoc(1), manpages(5), markdown(7), roff(7), ronn\-format(7)
