#!/bin/sh

# shellcheck source=libexec/enve/baselib
. "$ENVE_HOME/enve/baselib"

# shellcheck source=libexec/enve/tablelib
. "$ENVE_HOME/enve/tablelib"

settrace

# x='
# config.clearEnv
# config.shell
# layout.root
# layout.var
# path
# passvar
# variable
# command
# require.python.pipfile
# require.node.npmfile
# require.ruby.gemfile
# import
# module
# '


main() {
    info "IN $ZERO/enve.module"
    TABLE=$(cat "${configfile:--}")
    # for proc in first basic command nix terminal prompt macos ssh \
    #             shell secret boundfiles; do
    # for proc in nix; do

    #     info "IN resolve_$proc"
    #     if ! TABLE=$(TABLE=$TABLE resolve_$proc); then
    #         _error "error at resolve_$proc"
    #         exit 1
    #     fi
    #     # info "OUT resolve_$proc"
    # done

    info "OUT $ZERO/enve.module"
    [ -n "$TABLE" ] && printf %s\\n "$TABLE"
}

# if [ "${TEST:-}" != "test" ]; then
# fi

