#!/bin/sh

# shellcheck source=libexec/enve/base
. "$ENVE_HOME/enve/base"

settrace

prj_path=${1:-${PRJROOT:-}}
if [ -z "$prj_path" ]; then
    return 1
fi

if [ -n "${prj_path#${HOME%/}}" != "${prj_path}" ]; then
    prj="~${prj_path#${HOME%/}}"
else
    prj=$prj_path
fi


getwintitle="$ENVE_HOME/enve/core/macos/getwintitle.applescript"
sublime_merge=~/"Applications/Sublime\ Merge.app/Contents/MacOS/sublime_merge"
sublime_smerge=~/"Applications/Sublime\ Merge.app/Contents/SharedSupport/bin/smerge"

do_daemonlize() {
    if [ -n "${TMUX_SOCKET:-}" ]; then
        _exec_reparent_tmux "$sublime_merge" "$prj_path"
    else
        _exec_reparent_nohup "$sublime_merge" "$prj_path"
    fi
}

if [ -n "$(/usr/bin/osascript "$getwintitle" "sublime_merge"  "$prj" --raise)" ]; then
    :
# elif [ -n "$(/usr/bin/osascript "$getwintitle" "sublime_merge")" ]; then
#     # Sublime Merge is open, but no project window
#     "$sublime_smerge" --new-window "$prj_path"
else
    # Sublime Merge is not open
    do_daemonlize
    #"$sublime_smerge" --new-window "$prj_path"
fi

