#!/usr/bin/env enve

; [nix]
; channel.version=19.09

[enve]
bound.nocwd=true

[enve.shell]
friendly=true

[alias]
ls=lsd
tree=lsd -l --header --icon=always --color=always --tree | less
tree2=lsd -l --header --icon=always --color=always --tree --depth=2 | less
cat=bat --style="numbers,changes,header" --pager="less -RF"
less=less




; [module]
; oh-my-zsh

; [shell]
; zsh

; [nix]
; channel.version=18.09

; [nix.require]
; zsh

; [oh-my-zsh.plugins]
; git
; mafredri/zsh-async
; sindresorhus/pure
; zsh-users/zsh-completions
; zsh-users/zsh-autosuggestions
; zsh-users/zsh-syntax-highlighting

