#shell /usr/local/bin/enve boot
#shell ${ENVE_HOME}/../bin/enve -VVVV --pause-on-error fire boot
shell /usr/local/bin/enve -VVVV --pause-on-error fire boot

font_family       Hack Nerd Font Mono
font_size 14

confirm_os_window_close 2
macos_quit_when_last_window_closed yes

repaint_delay 50
input_delay 50

tab_bar_edge top
adjust_line_height 1
adjust_column_width -1


# window_border_width 0.5
# draw_minimal_borders yes
window_padding_width 1.0
# window_margin_width 0.1



wheel_scroll_multiplier 2.5

map cmd+left send_text all \x1b[H
map cmd+right send_text all \x1b[F

tab_bar_min_tabs 1
tab_title_template {title}

map ctrl+page_up    previous_tab
map ctrl+page_down  next_tab

# -- use tmux buffer --
map page_down send_text all \x1b[6~
map shift+page_down send_text all \x1b[6~
# map shift+up        scroll_line_up
# map shift+down      scroll_line_down
# map shift+page_up   scroll_page_up
# map shift+page_down scroll_page_down
# map shift+home      scroll_home
# map shift+end       scroll_end
# map shift+page_down show_scrollback


map ctrl+alt+w kitten signal_child_maybe_tmux.py SIGTERM \\x17
map cmd+c copy_or_interrupt
map cmd+z signal_child SIGTSTP
map cmd+shift+z send_text all \x18
map cmd+equal increase_font_size

# TODO: detect foreground is in tmux
# tmux last-window
map cmd+[ send_text all \x02l
# tmux next-window
map cmd+] send_text all \x02n


# allow_remote_control socket-only
allow_remote_control yes
listen_on unix:/tmp/kitty.sock

mouse_hide_wait 0

macos_option_as_alt left


# map ctrl+l kitten resize.py next_layout
# map ctrl+equal kitten resize.py larger
# map ctrl+minus kitten resize.py smaller
# map ctrl+s kitten sticky.py save-or-rename
# map ctrl+shift+r kitten sticky.py record "" "" --- --- /bin/sh -i

# map ctrl+left neighboring_window left
# map ctrl+right neighboring_window right
# map ctrl+up neighboring_window up
# map ctrl+down neighboring_window down

# map ctrl+shift+up move_window up
# map ctrl+shift+left move_window left
# map ctrl+shift+right move_window right
# map ctrl+shift+down move_window down

# map CMD+SHIFT+T reopen close session
# map ctrl+k kitten mykitten.py reopen close session

include kitty-theme.conf
include ${HOME}/.config/kitty/kitty.conf

