#!/usr/bin/env bash
set -euo pipefail
. "$1" define

echo IN $0 >&2

repourl() {
    repo_branch="$1"
    repo="${1%\#*}"
    if [ "$repo" != "$repo_branch" ]; then
        branch="${1##*\#}"
    else
        branch=
    fi

    if [ -e "${repo}/.git" ]; then
        repo="git+file://$repo"
    else
        # Sourced from antigen url resolution logic.
        # https://github.com/zsh-users/antigen/blob/master/antigen.zsh
        # Expand short github url syntax: `username/reponame`.
        case $repo in
            git+ssh://*|git+file://*|git+http://*|git+https://*|git+git@*:*)
                    :
                ;;
            ssh://*|file://*|http://*|https://*|git@*:*)
                    repo="git+$repo"
                ;;
            *)
                    repo="git+https://github.com/${repo%.git}.git"
                ;;
        esac
    fi
    if [ -n "$branch" ]; then
        echo "${repo}#${branch}"
    else
        echo "${repo}"
    fi
}



get-zsh(){
    if [ -z "${ZGEN_OH_MY_ZSH_REPO}" ]; then
        ZGEN_OH_MY_ZSH_REPO=robbyrussell
    fi

    if [ "${ZGEN_OH_MY_ZSH_REPO##*/}" != "${ZGEN_OH_MY_ZSH_REPO}" ]; then
        ZGEN_OH_MY_ZSH_REPO="${ZGEN_OH_MY_ZSH_REPO}/oh-my-zsh"
    fi
    if [ -z "${ZGEN_PREZTO_BRANCH}" ]; then
        ZGEN_PREZTO_BRANCH=master
    fi
    fetch "$(repourl "$ZGEN_OH_MY_ZSH_REPO#$ZGEN_OH_MY_ZSH_BRANCH")" %cache dir
}


-zgen-add-to-fpath() {

    # Add the directory to ZGEN_COMPLETIONS array if not present
    if [[ ! "${ZGEN_COMPLETIONS[@]}" =~ ${1} ]]; then
        ZGEN_COMPLETIONS+=("${1}")
    fi
}

-zgen-source() {
    local file="${1}"

    if [[ ! "${ZGEN_LOADED[@]}" =~ "${file}" ]]; then
        ZGEN_LOADED+=("${file}")
        source "${file}"

        completion_path="${file:h}"
        -zgen-add-to-fpath "${completion_path}"
    fi
}


zgen-load() {
    if [ "$#" == 0 ]; then
        -zgpute '`load` requires at least one parameter:'
        -zgpute '`zgen load <repo> [location] [branch]`'
    elif [[ "$#" == 1 && ("${1[1]}" == '/' || "${1[1]}" == '.' ) ]]; then
        local location="${1}"
    else
        local repo="${1}"
        local file="${2}"
        local branch="${3:-master}"
        local dir="$(-zgen-get-clone-dir ${repo} ${branch})"
        local location="${dir}/${file}"
        location=${location%/}

        # clone repo if not present
        if [[ ! -d "${dir}" ]]; then
            zgen-clone "${repo}" "${branch}"
        fi
    fi

    # source the file
    if [[ -f "${location}" ]]; then
        -zgen-source "${location}"

    elif [[ -f "${location}.zsh-theme" ]]; then
        -zgen-source "${location}.zsh-theme"

    elif [[ -f "${location}.theme.zsh" ]]; then
        -zgen-source "${location}.theme.zsh"

    elif [[ -f "${location}.zshplugin" ]]; then
        -zgen-source "${location}.zshplugin"

    elif [[ -f "${location}.zsh.plugin" ]]; then
        -zgen-source "${location}.zsh.plugin"

    # Classic oh-my-zsh plugins have foo.plugin.zsh
    elif -zgen-path-contains "${location}" ".plugin.zsh" ; then
        for script (${location}/*\.plugin\.zsh(N)) -zgen-source "${script}"

    elif -zgen-path-contains "${location}" ".zsh" ; then
        for script (${location}/*\.zsh(N)) -zgen-source "${script}"

    elif -zgen-path-contains "${location}" ".sh" ; then
        for script (${location}/*\.sh(N)) -zgen-source "${script}"

    # Completions
    elif [[ -d "${location}" ]]; then
        -zgen-add-to-fpath "${location}"

    else
      if [[ -d ${dir:-$location} ]]; then
        -zgpute "Failed to load ${dir:-$location} -- ${file}"
      else
        -zgpute "Failed to load ${dir:-$location}"
      fi
    fi
}

gencode() {
    -zginit "ZSH=$(get-zsh)"
    for file in "${ZGEN_LOADED[@]}"; do
        # TODO: LOADED_PLUGINS
        # -zginit 'LOADED_PLUGINS+=( "geometry-zsh/geometry" )'
        -zginit 'ZERO='\'"${file}"\'' source '\'"${file}"\'
    done

    # Set up fpath, load completions
    # NOTE: This *intentionally* doesn't use ${ZGEN_COMPINIT_FLAGS}; the only
    #       available flags are meaningless in the presence of `-C`.
    -zginit ""
    -zginit "# ### Plugins & Completions"
    -zginit 'fpath=('"${(@q)ZGEN_COMPLETIONS}"')'
    # if [[ ${ZGEN_AUTOLOAD_COMPINIT} == 1 ]]; then
    -zginit ""
    -zginit 'autoload -Uz compinit && \'
    -zginit '   compinit -C '"${ZGEN_COMPINIT_DIR_FLAG}"
    # fi
}

