#!/bin/sh

# shellcheck source=libexec/enve/base
. "$ENVE_HOME/enve/base"

# shellcheck source=libexec/enve/envelib
. "$ENVE_HOME/enve/envelib"

settrace

resolve_terminal() {
    [ -n "$TABLE" ] && echo "$TABLE"
    d=$(table_tail "SHELL")
    fast_basename
    shell=$d

    PRJ_NAME="$(table_tail "PRJ_NAME")"
    hist_dir=$HOME/.config/shell-history
    hist_file=$hist_dir/$PRJ_NAME.hist
    if [ ! -e "$hist_dir" ]; then
        mkdir -p "$hist_dir"
    fi

    out_code "sh" 'HISTFILE="'$hist_file'"'
    out_code "sh" 'HISTSIZE=10000'
    case $shell in
        dash|ash|ksh|sh)
            ;;
        bash)
                out_code "sh" 'HISTFILESIZE=20000'
                out_code "sh" 'HISTIGNORE="&:[ ]*:exit"'
                out_list ENVE_BASHOPTS "histappend"
                out_list ENVE_BASHOPTS "histverify"
            ;;
        zsh)
                out_code "sh" 'HISTFILESIZE=20000'
                out_code "sh" 'HISTORY_IGNORE="(exit)"'
                out_list ENVE_ZSHOPTS "inc_append_history"
                out_list ENVE_ZSHOPTS "hist_ignore_dups"
                out_list ENVE_ZSHOPTS "hist_ignore_space"
                out_list ENVE_ZSHOPTS "hist_verify"
                out_list ENVE_ZSHOPTS "-extended_history"
            ;;
    esac
    if [ "$shell" != "zsh" ]; then
        while read -r line; do
            out_code sh "$line"
        done < "$ZERO/prompt.sh"
    fi

    # given_shell=$(table_tail "shell")
    # if [ -n "$given_shell" ]; then
    #     out_var SHELL "$given_shell"
    # fi
}

main() {
    info "IN $(basename $ZERO)/enve.module"
    TABLE=$(cat "${configfile:--}")

    # shellcheck disable=2043
    for proc in terminal; do
        info "IN resolve_$proc"
        if ! TABLE=$(TABLE=$TABLE resolve_$proc); then
            _error "error at resolve_$proc"
            exit 1
        fi
        # info "OUT resolve_$proc"
    done

    info "OUT $(basename $ZERO)/enve.module"
    [ -n "$TABLE" ] && echo "$TABLE"
}

# if [ "${TEST:-}" != "test" ]; then
# fi

